services:
  group1:
    build:
      context: .
      dockerfile: Dockerfile
    # teams *may* crash the container, if they aren't careful
    restart: no # default 
    ports:
      - "3001:8080" # 300x number is the port for this group
    environment:
      - PASSWORD=${PASSWORD_GROUP1}

  group2:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    ports:
      - "3002:8080"
    environment:
      - PASSWORD=${PASSWORD_GROUP2}

  group3:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    ports:
      - "3003:8080"
    environment:
      - PASSWORD=${PASSWORD_GROUP3}
  
  group4:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    ports:
      - "3004:8080"
    environment:
      - PASSWORD=${PASSWORD_GROUP4}